version: '3.3'
services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 33069:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
